2020 12 msa feature
ebi-uniprot/uniprot-website pull request #221
Opened 2020-11-11 09:31 UTC by dlrice

- [x] What is the link to the Jira that this PR is for?
[Clicking on a feature in the protvista-tracks in BLAST and Align should trigger the display the corresponding tooltip.](https://www.ebi.ac.uk/panda/jira/browse/TRM-24863)
- [x] Have you written tests and do these have >= 75% coverage of the code that you are contributing?
- [x] Is it possible to visually evaluate this PR in the browser? If so, what are the steps to do this (eg specific URLs or sections)?
Both align and BLAST results
- [x] Are there any linting errors that required you to add exceptions?
Do not consider `useCustomElement`'s argument (which is just an import function) for the code coverage calculations.

# Change Summary
* Clicking on a feature in either track or MSA opens `protvista-tooltip`.
* Use `protvista-feature-adapter`'s `formatTooltip` to try to recreate content display of existing protvista's tooltip. Data passed to `prepareFeatureForTooltip` before passing `formatTooltip`.
* MSA feature border color reflects track feature color (`getColorByType` now exported from 'protvista-track').
* Feature track label includes active accession.

2020-11-11 14:09 UTC, aurel-l requested changes
Globally OK with the majority of changes.

Some small comments here and there.

And I found one edge case where if none of the sequences has annotations (edited sequences, or accession-less sequences). In the wrapped view, the spaces allocated to the feature tracks in the grid is occupied by the alignment tracks and it's all messed up.
It should maybe render an empty element to use this space in the grid, instead of rendering undefined.

2020-11-12 18:05 UTC, dlrice commented on src/tools/components/Wrapped.tsx
> +      activeAlignment?.from,
The `activeAlignment?.*` was auto-suggested and we've changed this to now consider `activeAlignment` instead.

2020-11-12 18:05 UTC, dlrice commented
Addressed all comments. Ready for re-review.

2020-11-12 18:08 UTC, dlrice commented on src/tools/components/AlignmentView.tsx
> +      passive: false,
Needed for when the page is scrollable and the user scrolls which will leave the tooltip fixed in place.

2020-11-13 08:54 UTC, aurel-l approved these changes

2020-11-13 09:26 UTC, merged